### PR TITLE
Be able to add a comment

### LINKED ISSUE #5: Comment on idea // 5
In order to help the idea starter as an idea commenter I want to be able to post a comment
- [x] Create a Comment model
- [x] Create an add comment action in the idea controller
- [x] Implement comment abilities in the idea view
- [x] Implement translations in YAML

### PR DESCRIPTION
**Pull request by dennisdegreef**
Closes #5 and #6

Now has a comment field with a submit button and takes the user logged in as commenter

### CODE REVIEW

**Comment by dennisdegreef** [comment]
@piwi91 Could you take a look at this?

**Comment by Joralf** [comment]
LGTM :+1:

**Comment by piwi91** [comment]
:+1:

**Comment by ussuritiger** [comment]
:+1:

**Pull request merged**
